put -r ./public/* .var/www/dungeonlooter.ru/
put -r ./src/* .var/www/dungeonlooter.ru/
put -r ./package.json .var/www/dungeonlooter.ru/
put -r ./next.config.mjs .var/www/dungeonlooter.ru/
put -r ./.next/* .var/www/dungeonlooter.ru/
put -r ./tsconfig.json .var/www/dungeonlooter.ru/
put -r ./next-env.d.ts .var/www/dungeonlooter.ru/
put -r ./jest.config.ts .var/www/dungeonlooter.ru/
put -r ./.eslintrc.json .var/www/dungeonlooter.ru/
put -r ./tsconfig.json .var/www/dungeonlooter.ru/