put -r ./public/* coolAppName
put -r ./src/* coolAppName
put -r ./package.json coolAppName
put -r ./next.config.mjs coolAppName
put -r ./.next/* coolAppName
put -r ./tsconfig.json coolAppName
put -r ./next-env.d.ts coolAppName
put -r ./jest.config.ts coolAppName
put -r ./.eslintrc.json coolAppName
put -r ./tsconfig.json coolAppName