name: Check
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint  
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }} # Your server's IP address
          username: ${{ secrets.FTP_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /var/www/dungeonlooter.ru # Specify the path to your app directory on the server
            git pull
            npm install
            npm run build
            pm2 start npm -- start --name dl # Replace with your PM2 service name