name: Check
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint  
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: 'root'
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          uploads: |
            ./ => ./www/dungeonlooter.ru/
          ignore: |
            */node_modules