name: Check
on: push
jobs:
  deploy:
    strategy:
      matrix:
        path: [./public/*, ./src/*, ./package.json, ./next.config.mjs, ./.next/*, ./tsconfig.json, ./next-env.d.ts, ./jest.config.ts, ./.eslintrc.json]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint  
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.FTP_SERVER }}'
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ${{ matrix.path }}
          remote_path: '/var/www/dungeonlooter.ru'
          args: '-o ConnectTimeout=5' 