name: Check
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint  
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: Luis97lol/PSFTP@v1.4
        with:
          user: 'root'
          host: ${{ secrets.FTP_SERVER }}
          pass: ${{ secrets.FTP_PASSWORD }}
          scriptPath: deploy.sh